version: '3.7'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_HOST=db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
